#!/bin/bash
# Every command that users run directly adopts lib/run-log.sh: it sources the
# library and calls run_log_start at top level, before parsing its arguments,
# and doesn't exec into another program (which would skip the log's footer).
#
# Usage: scripts/bash/tests/test-run-log-adoption.sh
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PASS=0
FAIL=0
check(){ if [ "$2" = "$3" ]; then PASS=$((PASS + 1)); echo "  ok   $1"; else FAIL=$((FAIL + 1)); echo "  FAIL $1 (expected '$3', got '$2')"; fi; }

# script|command name|read-only
ADOPTERS=(
  "build.sh|build|"
  "deploy.sh|deploy|"
  "setup.sh|setup|"
  "cleanup.sh|cleanup|"
  "modules.sh|modules|"
  "update-latest.sh|update-latest|"
  "status.sh|status|--read-only"
  "changelog.sh|changelog|--read-only"
  "scripts/bash/backup-export.sh|backup-export|"
  "scripts/bash/backup-import.sh|backup-import|"
  "scripts/bash/migrate-stack.sh|migrate-stack|"
  "scripts/bash/repair-storage-permissions.sh|repair-storage-permissions|"
)

for entry in "${ADOPTERS[@]}"; do
  IFS='|' read -r script name ro <<< "$entry"
  f="$REPO_ROOT/$script"
  echo "$script"
  start_line="$(grep -nE "^run_log_start ${name} ${ro:+$ro }-- \"\\\$@\"; set -- \"\\\$\{RUN_LOG_ARGS\[@\]\}\"$" "$f" | head -1 | cut -d: -f1)"
  check "calls run_log_start $name ${ro} at top level" "$([ -n "$start_line" ] && echo yes || echo no)" "yes"
  check "sources lib/run-log.sh" "$(grep -cE '^source ".*scripts/bash/lib/run-log\.sh"$|^source "\$SCRIPT_DIR/lib/run-log\.sh"$' "$f")" "1"
  parse_line="$(grep -nE '^while \[\[? \$# -gt 0' "$f" | head -1 | cut -d: -f1)"
  if [ -n "$parse_line" ] && [ -n "$start_line" ]; then
    check "before argument parsing" "$([ "$start_line" -lt "$parse_line" ] && echo yes || echo no)" "yes"
  fi
  check "no exec into another program" "$(grep -cE '^\s*exec [^{0-9<>]' "$f")" "0"
  check "bash -n" "$(bash -n "$f" 2>&1 && echo ok)" "ok"
done

echo "compose never mounts logs/"
check "logs/ not in docker-compose.yml" "$(grep -cE '(^|[^a-z_])logs/?:' "$REPO_ROOT/docker-compose.yml" | awk '{print ($1>0)?"mounted":"no"}')" "no"

echo "migrate-stack --copy-source leaves logs/ behind"
check "tar excludes ./logs" "$(grep -cE "^\s*if ! tar .*--exclude='\./logs'" "$REPO_ROOT/scripts/bash/migrate-stack.sh")" "1"

echo "setup writes LOG_KEEP_RUNS into .env"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
# Source the real .env writer with its helpers stubbed; $0 picks the output dir.
setup_env_out(){
  # shellcheck disable=SC2016  # expanded by the inner bash
  env "$@" TEMPLATE_FILE="$REPO_ROOT/.env.template" LOCAL_STORAGE_ROOT_ABS="$WORK/ls" bash -c '
    source "'"$REPO_ROOT"'/scripts/bash/lib/common.sh"
    source "'"$REPO_ROOT"'/scripts/bash/setup/env.sh"
    say(){ :; }; ask_yn(){ echo 1; }
    sanitize_project_name(){ echo test; }; resolve_project_image_tag(){ echo "img:$2"; }
    HEALTHCHECK_KEYS=(); MODULE_KEYS=(); FORCE_OVERWRITE=1
    setup_write_env
  ' "$WORK/setup.sh" >/dev/null 2>&1
  grep -E "^LOG_KEEP_RUNS=" "$WORK/.env" 2>/dev/null || echo "missing"
}
check "env writer ran" "$(setup_env_out >/dev/null; grep -c '^# Generated by setup.sh' "$WORK/.env")" "1"
check "default from .env.template" "$(setup_env_out -u LOG_KEEP_RUNS)" "LOG_KEEP_RUNS=30"
check "value from the environment" "$(setup_env_out LOG_KEEP_RUNS=7)" "LOG_KEEP_RUNS=7"
check "comment block from .env.template" "$(grep -c '^# How many logs to keep per command' "$WORK/.env")" "1"

echo
echo "passed: $PASS  failed: $FAIL"
[ "$FAIL" -eq 0 ]
